### ISSUE TITLE
Error with multiple strings in the same line

### ISSUE THREAD

**Issue by justinmchase** [nomilous/node-required#1]
This throws an error fyi:

```
const debug = require('debug')('example')
```

With the error:

```
Error: Cannot find module 'debug')('example'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/justin/.nvm/versions/node/v5.2.0/lib/node_modules/node-required/bin/required:191:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
```

I'm assuming this has to do with a regular expression that is a little greedy.

[Probably this line](https://github.com/nomilous/node-required/blob/master/bin/required#L114)

**Comment by justinmchase** [comment]
I think this is a real issue still but I don't want to see it in my issue list anymore.
